public class ControleProdutos {
    public static void main(String[] args) {
    
    String nomeDoSmartphone = "SamsungM14";
    String marcaDoSmartphone = "Samsung";
    double precoDoSmartphone = 2000.00;
    Integer quantidadeEstoqueSmartphone = 10;
    
    String nomeDoLaptop= "Lenovo15";
    String marcaDoLaptop = "Lenovo";
    double precoDoLaptop = 2800.00;
    Integer quantidadeEstoqueLaptop = 14;
    
    String nomeDoFoneDeOuvidoBluetooth= "LenovoXT80";
    String marcaDoFoneDeOuvidoBluetooth = "Xiaomi";
    double precoDoFoneDeOuvidoBluetooth = 90.00;
    Integer quantidadeFoneDeOuvidoBluetooth = 20;
    
    System.out.println("*Smartphone************************************");
    System.out.println("Dados do Smartphone:");
    System.out.println("Nome: " + nomeDoSmartphone);
    System.out.println("Marca: " + marcaDoSmartphone);
    System.out.println("Preco: " + precoDoSmartphone);
    System.out.println("Quantidade: " + quantidadeEstoqueSmartphone);
    
    System.out.println("**Laptop******************************************");
    System.out.println("Dados do Laptop:");
    System.out.println("Nome: " + nomeDoLaptop);
    System.out.println("Marca: " + marcaDoLaptop);
    System.out.println("Preco: " + precoDoLaptop);
    System.out.println("Quantidade: " + quantidadeEstoqueLaptop);
    
    System.out.println("*Laptop***Fone de Ouvido Bluetooth*****************");
    System.out.println("Dados do Fone de Ouvido Bluetooth:");
    System.out.println("Nome: " + nomeDoFoneDeOuvidoBluetooth);
    System.out.println("Marca: " + marcaDoFoneDeOuvidoBluetooth);
    System.out.println("Preco: " + precoDoFoneDeOuvidoBluetooth);
    System.out.println("Quantidade: " + quantidadeFoneDeOuvidoBluetooth);
    }
}
